version: '3.1'

services:

  mysql:
    hostname: ${NAME}-mysql
    container_name: ${NAME}-mysql
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD:  ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:       ${MYSQL_DATABASE}
      MYSQL_USER:           ${MYSQL_USER}
      MYSQL_PASSWORD:       ${MYSQL_PASSWORD}
    volumes:
      - /docker/mysql/data:/var/lib/mysql
      - /docker/mysql/utf8.cnf:/etc/mysql/conf.d/utf8.cnf